[project]
name = "hue-mcp"
version = "0.1.0"
description = "MCP Server for Philips Hue control"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "phue>=1.1",
    "python-dotenv>=1.1.0",
]
